
export function useCatalogData() {
    const gpuData = {
    nvidia: {
        a100: {
        name: "NVIDIA A100 Tensor Core",
        architecture: "Ampere",
        memory: "80GB HBM2e",                    
        memoryBandwidth: "1.9–2.0 TB/s",        
        fp32: "19.5 TFLOPS",                      
        fp64: "9.7 TFLOPS",                       
        fp16Tensor: "312 TFLOPS",                 
        int8: "624 TOPS",                        
        fp8: "N/A (no native support)",
        power: "300–400W",                        
        formFactors: ["PCIe", "SXM"],
        },
        h100: {
        name: "NVIDIA H100 Tensor Core",
        architecture: "Hopper",
        memory: "80GB HBM3",                     
        memoryBandwidth: "3.35 TB/s",            
        fp16Tensor: "1.98 PFLOPS",               
        fp8Tensor: "3.96 PFLOPS",                 
        fp32Tensor: "1.98 TFLOPS (approx)",       
        memoryType: "HBM3",
        power: "≈700W",                           
        formFactors: ["PCIe", "SXM"],
        },
        h200: {
        name: "NVIDIA H200 Tensor Core",
        architecture: "Hopper (enhanced)",
        memory: "141GB HBM3e",                   
        memoryBandwidth: "4.8 TB/s",              
        fp8Tensor: "4.0 PFLOPS",                  
        fp16Tensor: "≈2.0 PFLOPS",               
        fp32Tensor: "≈2.0 TFLOPS (approx)",
        memoryType: "HBM3e",
        power: "≈700–800W",
        formFactors: ["PCIe", "SXM"],
        },
    },
    amd: {
        mi250x: {
        name: "AMD Instinct MI250X",
        architecture: "CDNA3",
        memory: "128GB HBM3",                    
        memoryBandwidth: "≈3.2–3.3 TB/s",
        fp16: "≈383 TFLOPS",                     
        fp64: "≈47.9 TFLOPS",                     
        int8: "≈383 TOPS",
        power: "≈560W",                           
        memoryType: "HBM3",
        },
        mi300x: {
        name: "AMD Instinct MI300X",
        architecture: "CDNA3",
        memory: "192GB HBM3",                     
        memoryBandwidth: "5.3 TB/s",              
        peakFP16: "1307.4 TFLOPS",                 
        peakFP8: "2614.9 TFLOPS",                  
        fp32: "163.4 TFLOPS",                      
        fp64: "81.7 TFLOPS",                      
        power: "≈750W",                           
        memoryType: "HBM3",
        },
        mi325x: {
        name: "AMD Instinct MI325X",
        architecture: "CDNA3",
        memory: "256GB HBM3E",                     
        memoryBandwidth: "6.0 TB/s",               
        computeUnits: 304,
        fp16: "≈1307 TFLOPS",                      
        fp8: "≈2614 TOPS",                         
        power: "≈1000W",                          
        memoryType: "HBM3E",
        },
        mi355x: {
        name: "AMD Instinct MI355X",
        architecture: "CDNA4",
        memory: "288GB HBM3E",                     
        memoryBandwidth: "8.0 TB/s",              
        peakFP16: "≈5033 TFLOPS (sparsity)",        
        peakFP8: "≈10.1 PFLOPS",                    
        fp32: "≈157.3 TFLOPS",                     
        fp64: "≈78.6 TFLOPS",                       
        power: "≈1000W+",                           
        memoryType: "HBM3E",
        },
    }
    };


    return { gpuData };
}